[tool.poetry]
name = "math"
version = "0.1.0"
description = ""
authors = ["u-masao <4973920+u-masao@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
reportlab = "^3.5.47"
black = "^19.10b0"
flake8 = "^3.8.3"
mypy = "^0.782"
click = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
