# Generated by Django 3.1 on 2020-08-22 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0003_auto_20200822_2342"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorythm",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="algorythm",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
