# Generated by Django 3.1 on 2020-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0006_auto_20200822_2359"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="a",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="ab_max",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="question",
            name="ab_min",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="ans_max",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="question",
            name="ans_min",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="b",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="pages",
            field=models.IntegerField(default=5),
        ),
    ]
