# Generated by Django 3.1 on 2020-08-22 15:17

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command(
        "loaddata", "sheets/fixture/0009/algorythms.json", app_label="sheets"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0008_remove_question_params_text"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
