# Generated by Django 3.1 on 2020-08-23 03:00

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command(
        "loaddata", "sheets/fixture/0011/algorythms.json", app_label="sheets"
    )

    call_command(
        "loaddata", "sheets/fixture/0010/questions.json", app_label="sheets"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_auto_20200823_0023'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]

