# Generated by Django 3.1 on 2020-09-06 05:47
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command(
        "loaddata", "sheets/fixture/0013/algorythms.json", app_label="sheets"
    )

    call_command(
        "loaddata", "sheets/fixture/0013/questions.json", app_label="sheets"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0012_auto_20200824_2103'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
