# Generated by Django 3.1 on 2020-11-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0014_auto_20201031_0842"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="style",
            field=models.CharField(
                choices=[("formura", "式"), ("sentence", "文章問題")],
                default="formura",
                max_length=10,
                verbose_name="問題の形式",
            ),
        ),
    ]
