# Generated by Django 3.1 on 2020-08-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Chice", new_name="Choice",),
    ]
