# Generated by Django 3.1 on 2020-08-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_auto_20200815_2223"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice", old_name="voets", new_name="votes",
        ),
    ]
