# Generated by Django 3.1 on 2020-08-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="date created")),
                (
                    "modified",
                    models.DateTimeField(verbose_name="date modified"),
                ),
                ("theme_text", models.CharField(max_length=200)),
                ("level_text", models.CharField(max_length=20)),
                ("level_number", models.IntegerField(default=0)),
                ("action", models.CharField(max_length=100)),
                ("params_text", models.CharField(max_length=100)),
            ],
        ),
    ]
