# Generated by Django 3.1 on 2022-01-29 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Algorythm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("usage", models.CharField(max_length=300)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("theme_text", models.CharField(max_length=200)),
                ("level_text", models.CharField(max_length=20)),
                ("level_number", models.IntegerField(default=0)),
                ("pages", models.IntegerField(default=5)),
                ("ans_min", models.IntegerField(default=0)),
                ("ans_max", models.IntegerField(default=10)),
                ("ab_min", models.IntegerField(default=0)),
                ("ab_max", models.IntegerField(default=10)),
                ("a", models.IntegerField(default=0)),
                ("b", models.IntegerField(default=0)),
                ("a_min", models.IntegerField(default=0)),
                ("a_max", models.IntegerField(default=10)),
                ("b_min", models.IntegerField(default=0)),
                ("b_max", models.IntegerField(default=10)),
                (
                    "style",
                    models.CharField(
                        choices=[("formura", "式"), ("sentence", "文章問題")],
                        default="formura",
                        max_length=10,
                        verbose_name="問題の形式",
                    ),
                ),
                (
                    "algorythm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheets.algorythm",
                    ),
                ),
            ],
        ),
    ]
