# Generated by Django 3.1 on 2022-01-29 15:13

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "sheets/fixture/0002/algorythms.json", app_label="sheets")
    call_command("loaddata", "sheets/fixture/0002/questions.json", app_label="sheets")


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
