# Generated by Django 3.2.11 on 2022-01-30 08:23

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "sheets/fixture/0003/algorythms.json", app_label="sheets")
    call_command("loaddata", "sheets/fixture/0003/questions.json", app_label="sheets")


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0002_auto_20220129_1513"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
