# Generated by Django 3.1 on 2020-08-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0002_auto_20200822_2316"),
    ]

    operations = [
        migrations.CreateModel(
            name="Algorythm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("usage", models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name="question",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="question",
            name="algorythm",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheets.algorythm",
            ),
            preserve_default=False,
        ),
    ]
