# Generated by Django 3.1 on 2020-08-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0004_auto_20200822_2347"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="action",),
    ]
