# Generated by Django 3.1 on 2020-08-22 14:59

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "sheets/fixture/questions.json", app_label="sheets")

    call_command("loaddata", "sheets/fixture/algorythms.json", app_label="sheets")


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0005_remove_question_action"),
    ]

    operations = [
        # migrations.RunPython(load_fixture),
    ]
