# Generated by Django 3.2.11 on 2022-05-11 11:56

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "sheets/fixture/0007/algorythms.json", app_label="sheets")
    call_command("loaddata", "sheets/fixture/0007/questions.json", app_label="sheets")


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0006_auto_20220511_0041"),
    ]

    operations = [
        # migrations.RunPython(load_fixture),
    ]
