# Generated by Django 3.1 on 2020-08-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0007_auto_20200823_0010"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="params_text",
        ),
    ]
