# Generated by Django 3.2.11 on 2022-06-25 07:29

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "sheets/fixture/0010/algorythms.json", app_label="sheets")
    call_command("loaddata", "sheets/fixture/0010/questions.json", app_label="sheets")

class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_auto_20220625_0650'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
