# Generated by Django 3.2.13 on 2022-07-09 06:12

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "sheets/fixture/0012/algorythms.json", app_label="sheets")
    call_command("loaddata", "sheets/fixture/0012/questions.json", app_label="sheets")


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0011_auto_20220625_0729"),
    ]

    operations = [
        # migrations.RunPython(load_fixture),
    ]
