# Generated by Django 3.2.15 on 2022-10-29 04:57

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "sheets/fixture/0014/algorythms.json", app_label="sheets")
    call_command("loaddata", "sheets/fixture/0014/questions.json", app_label="sheets")


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0013_auto_20220812_0816"),
    ]

    operations = [
        # migrations.RunPython(load_fixture),
    ]
