# Generated by Django 3.2.15 on 2022-10-30 04:40

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "sheets/fixture/0014/algorythms.json", app_label="sheets")
    call_command("loaddata", "sheets/fixture/0014/questions.json", app_label="sheets")


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0014_auto_20221029_0457"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
