# Generated by Django 3.2.15 on 2022-12-26 03:37

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "sheets/fixture/0016/algorythms.json", app_label="sheets")
    call_command("loaddata", "sheets/fixture/0016/questions.json", app_label="sheets")


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0015_auto_20221030_0440"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
